# Generated by Django 2.1.3 on 2020-04-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_code',
            field=models.TextField(default='null', verbose_name='public_code'),
        ),
    ]
