# Generated by Django 2.1.3 on 2020-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200418_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public_code',
            field=models.CharField(choices=[('성결유치원', '3'), ('의석유치원', '4')], max_length=80, null=True),
        ),
    ]
