# Generated by Django 2.1.3 on 2020-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200507_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public_code',
            field=models.CharField(choices=[('성결유치원', '성결유치원'), ('의석유치원', '의석유치원')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='post2',
            name='personal_code',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
