# Generated by Django 3.0.4 on 2020-03-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeInfo',
            new_name='Info',
        ),
    ]
