# Generated by Django 2.2.5 on 2020-03-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200319_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={},
        ),
        migrations.AlterModelTable(
            name='info',
            table=None,
        ),
    ]
