# Generated by Django 2.1.3 on 2020-05-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_info_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='created_date',
        ),
    ]
