# Generated by Django 2.1.3 on 2020-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerOnOff', models.IntegerField(verbose_name='RaspberryPi Power On Off')),
            ],
            options={
                'verbose_name': '안드로이드 요청 데이터',
                'verbose_name_plural': '안드로이드 요청 데이터',
            },
        ),
    ]
