# Generated by Django 2.1.3 on 2020-06-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='personal_code',
            field=models.TextField(default='null', verbose_name='personal_code'),
        ),
    ]
