# Generated by Django 2.1.3 on 2020-06-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
