# Generated by Django 2.1.3 on 2020-05-20 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='null', verbose_name='name')),
                ('phone', models.TextField(default='null', verbose_name='phone')),
                ('kindergarden', models.TextField(default='null', verbose_name='kindergarden')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'RFID_데이터',
                'db_table': 'RFID',
            },
        ),
    ]
