# Generated by Django 2.1.3 on 2020-05-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='personal_code',
            field=models.TextField(default='null', verbose_name='personal_code'),
        ),
    ]
